#! /bin/sh
#
# BTest helper for getting values for Bro-related environment variables.

base=`dirname $0`
zeek=`cat ${base}/../../build/CMakeCache.txt | grep BRO_DIST | cut -d = -f 2`

if [ "$1" = "zeekbase" ]; then
    echo ${zeek}
elif [ "$1" = "zeekpath" ]; then
    ${zeek}/build/zeek-path-dev
elif [ "$1" = "zeek_plugin_path" ]; then
    ( cd ${base}/../.. && pwd )
elif [ "$1" = "zeek_seed_file" ]; then
    echo ${zeek}/testing/btest/random.seed
elif [ "$1" = "path" ]; then
    echo ${zeek}/build/src:${zeek}/aux/btest:${base}/:${zeek}/aux/zeek-cut:$PATH
else
    echo "usage: `basename $0` <var>" >&2
    exit 1
fi
